name: Verify Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: git_changes
        run: echo "::set-output name=files::$(git diff --name-only HEAD^..HEAD)"

      - name: Check for sysout
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
