name: Verify Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        run: echo "::set-output name=files::$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)"

      - name: Check for sysout
        run: |
          # Get changed files
          changed_files="${{ steps.changes.outputs.files }}"
          
          # Look for 'sysout' in changed files
          for file in $changed_files; do
            grep -qi 'sysout' $file && echo "sysout found in $file"
          done
