name: Verify Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: git_changes
        run: echo "::set-output name=files::$(git diff --name-only HEAD^..HEAD)"

      - name: Check for sysout
        run: |
          files="${{ steps.git_changes.outputs.files }}"
          for file in $files; do
            if grep -q 'sysout' "$file"; then
              echo "sysout found in $file"
              exit 1
            fi
          done
